[general]
import = [
  "~/.config/alacritty/dank-theme.toml"
]

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
# opacity = 0.8
# decorations = "None"
padding = { x = 4, y = 4 }
dynamic_padding = true

# [window.dimensions]
# columns = 180
# lines = 40

# [window.class]
# instance = "Alacritty"
# general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"
save_to_clipboard = true

# [cursor]
# style = "Underline"
# vi_mode_style = "None"
# unfocused_hollow = true
# thickness = 0.15

# [mouse]
# hide_when_typing = true

[keyboard]
bindings = [
  { key = "C",       mods = "Control|Shift", action = "Copy"  },
  { key = "V",       mods = "Control|Shift", action = "Paste" },
  { key = "N",       mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Equals",  mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus",   mods = "Control",       action = "DecreaseFontSize" },
  { key = "Key0",    mods = "Control",       action = "ResetFontSize"    },
  { key = "Enter",   mods = "Shift",         chars = "\n" },
]
